image: node:12

stages:
    - build
    - containerization
    - deploy

build_image:
    stage: build
    script:
        - docker build -t $BUILD_TAG .

#register the image only on Master Branch
register_image:
    stage: containerization
    variables:
        SHA: $CI_COMMIT_SHORT_SHA
        REGISTER_TAG: ${CI_PROJECT_NAME}_${CI_COMMIT_BRANCH}
        CONFIG: $CONFIG_PROD
    script:
        - docker tag $BUILD_TAG $DOCKER_SERVER/$REGISTER_TAG:$SHA
        - docker tag $BUILD_TAG $DOCKER_SERVER/$REGISTER_TAG:latest
        - docker push $DOCKER_SERVER/$REGISTER_TAG:$SHA
        - docker push $DOCKER_SERVER/$REGISTER_TAG:latest
    only:
        - master

deploy_to_dev:
    stage: deploy
    variables:
        RUN_TAG: $BUILD_TAG
        CONT_NAME: $BUILD_TAG
    script:
        - docker-compose down
        - docker-compose up -d
    only:
        - desarrollo
    tags:
        - desarrollo

deploy_to_prod:
    stage: deploy
    variables:
        RUN_TAG: ${DOCKER_SERVER}/${BUILD_TAG}:latest
        CONT_NAME: $BUILD_TAG
        PORT: $PORT
        MYSQL_SERVER: $MYSQL_SERVER
        MYSQL_PORT: $MYSQL_PORT
        MYSQL_DB: $MYSQL_DB
        MYSQL_USER: $MYSQL_USER
        MYSQL_PW: $MYSQL_PW
        DEPLOYMENT: $DEPLOYMENT
        SECRET_KEY: $SECRET_KEY
    script:
        - docker pull $RUN_TAG
        - docker-compose down
        - docker-compose up -d
    only:
        - master
    when: manual
    tags:
        - master