stages:
    - build
    - containerization
    - deploy
    
cache:
    paths:
        - node_modules/

install_dependencies:
    stage: build
    script:
        - npm install
    artifacts:
        paths:
            - node_modules/

containerization:
    stage: containerization # must match the stage name declared above
    script:
        # Build the container image
        - docker build -t thk/docker-test .
        # Push the container image to the registry
        #- docker push my-registry/my-application
        # Cleanup by removing the local image
        #- docker image rm my-registry/my-application

#deploy_app:
#    stage: deploy
#    script: npm start
