version: "2"

services:

    node-api-jwt:
        image: $BUILD_TAG:latest
        container_name: $CONT_NAME
        restart: always
        ports:  
            #El puerto expuesto en el caso de node debe ser el mismo por el que corre la app 
            - "$PORT:$PORT"
        environment:
            - MYSQL_SERVER=$MYSQL_SERVER
            - MYSQL_PORT=$MYSQL_PORT
            - MYSQL_DB=$MYSQL_DB
            - MYSQL_USER=$MYSQL_USER
            - MYSQL_PW=$MYSQL_PW
            # si se necesita trabajar con la base de datos local solo cambiar el valor de la variable DEPLOYMENT, no borrarla
            - PORT=$PORT
            - SECRET_KEY=$SECRET_KEY
        networks:
            - webnet            
networks:
    webnet: 
